-- Criação da tabela roleta_numeros para armazenar os números das roletas
CREATE TABLE roleta_numeros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roleta_id TEXT NOT NULL,
  roleta_nome TEXT NOT NULL,
  numero INTEGER NOT NULL CHECK (numero >= 0 AND numero <= 36),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para melhorar a performance das consultas
CREATE INDEX idx_roleta_numeros_roleta_id ON roleta_numeros(roleta_id);
CREATE INDEX idx_roleta_numeros_numero ON roleta_numeros(numero);
CREATE INDEX idx_roleta_numeros_created_at ON roleta_numeros(created_at);

-- Comentários para documentar a tabela
COMMENT ON TABLE roleta_numeros IS 'Armazena os números extraídos de cada roleta';
COMMENT ON COLUMN roleta_numeros.roleta_id IS 'ID da roleta';
COMMENT ON COLUMN roleta_numeros.roleta_nome IS 'Nome da roleta para facilitar consultas';
COMMENT ON COLUMN roleta_numeros.numero IS 'Número extraído da roleta (0-36)';
COMMENT ON COLUMN roleta_numeros.created_at IS 'Data e hora em que o número foi extraído';

-- Função para limitar o número de registros por roleta (opcional)
CREATE OR REPLACE FUNCTION limit_roleta_numeros() RETURNS TRIGGER AS $$
DECLARE
  max_records_per_roleta INTEGER := 1000; -- Limite de 1000 números por roleta
  current_count INTEGER;
  oldest_records RECORD;
BEGIN
  -- Contar quantos registros existem para esta roleta
  SELECT COUNT(*) INTO current_count 
  FROM roleta_numeros 
  WHERE roleta_id = NEW.roleta_id;
  
  -- Se exceder o limite, remover os registros mais antigos
  IF current_count >= max_records_per_roleta THEN
    FOR oldest_records IN (
      SELECT id FROM roleta_numeros 
      WHERE roleta_id = NEW.roleta_id 
      ORDER BY created_at ASC 
      LIMIT (current_count - max_records_per_roleta + 1)
    ) LOOP
      DELETE FROM roleta_numeros WHERE id = oldest_records.id;
    END LOOP;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para limitar o número de registros
CREATE TRIGGER trigger_limit_roleta_numeros
AFTER INSERT ON roleta_numeros
FOR EACH ROW
EXECUTE FUNCTION limit_roleta_numeros(); 