#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Script para criar a tabela roleta_numeros no Supabase usando a API REST
"""

import os
import logging
import json
import requests
from dotenv import load_dotenv

# Carregar variáveis de ambiente
load_dotenv()

# Configuração de logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('criar_tabela')

# Configuração do Supabase
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://evzqzghxuttctbxgohpx.supabase.co')
SUPABASE_KEY = os.getenv('SUPABASE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2enF6Z2h4dXR0Y3RieGdvaHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzc5OTEsImV4cCI6MjA1Njc1Mzk5MX0.CmoM_y0i36nbBx2iN0DlOIob3yAgVRM1xY_XiOFBZLQ')

def verificar_tabela():
    """Verifica se a tabela roleta_numeros existe"""
    logger.info("Verificando se a tabela roleta_numeros existe...")
    
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json"
    }
    
    # Tentar fazer uma consulta simples para verificar se a tabela existe
    url = f"{SUPABASE_URL}/rest/v1/roleta_numeros?limit=1"
    
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            logger.info("Tabela roleta_numeros existe!")
            logger.info("Verificando a estrutura da tabela...")
            
            # Vamos ver o esquema da tabela
            try:
                # Buscar informações da tabela
                logger.info("Estrutura da tabela:")
                return True
            except Exception as e:
                logger.error(f"Erro ao obter esquema da tabela: {str(e)}")
                return True
        else:
            logger.info(f"Tabela não encontrada. Código: {response.status_code}, Resposta: {response.text}")
            return False
    except Exception as e:
        logger.error(f"Erro ao verificar tabela: {str(e)}")
        return False

def criar_tabela_manual():
    """Cria a tabela roleta_numeros manualmente"""
    logger.info("Criando tabela roleta_numeros...")
    
    # Use um SQL statement para criar a tabela
    sql = """
    CREATE TABLE roleta_numeros (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      roleta_id TEXT NOT NULL,
      roleta_nome TEXT NOT NULL,
      numero INTEGER NOT NULL CHECK (numero >= 0 AND numero <= 36),
      cor TEXT,
      timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE INDEX idx_roleta_numeros_roleta_id ON roleta_numeros(roleta_id);
    CREATE INDEX idx_roleta_numeros_timestamp ON roleta_numeros(timestamp);
    """
    
    logger.info("Código SQL para criar a tabela:")
    logger.info(sql)
    logger.info("\nEntre no dashboard do Supabase (https://app.supabase.com/) e execute este SQL no editor de SQL")
    logger.info("Depois de criar a tabela manualmente, reinicie o servidor backend para que os dados possam ser inseridos corretamente")
    
    return True

if __name__ == "__main__":
    logger.info("Iniciando verificação/criação da tabela roleta_numeros...")
    
    if verificar_tabela():
        logger.info("Tabela já existe, não é necessário criá-la novamente.")
    else:
        criar_tabela_manual() 